In [1]:
from bs4 import BeautifulSoup
import requests
import numpy as np
import pandas as pd
from geopy.geocoders import Nominatim
import folium
import json
from pandas.io.json import json_normalize # tranform JSON file into a pandas dataframe
from sklearn.cluster import KMeans
import matplotlib.cm as cm
import matplotlib.colors as colors

In [2]:
url = 'https://en.wikipedia.org/wiki/List_of_postal_codes_of_Canada:_M'
result = requests.get(url)
print(url)
print(result.status_code)
print(result.headers)

https://en.wikipedia.org/wiki/List_of_postal_codes_of_Canada:_M
200
{'Date': 'Fri, 29 May 2020 05:36:04 GMT', 'Vary': 'Accept-Encoding,Cookie,Authorization', 'Server': 'ATS/8.0.7', 'Content-Type': 'text/html; charset=UTF-8', 'X-Content-Type-Options': 'nosniff', 'P3P': 'CP="See https://en.wikipedia.org/wiki/Special:CentralAutoLogin/P3P for more info."', 'Content-language': 'en', 'Last-Modified': 'Sat, 23 May 2020 19:32:34 GMT', 'Content-Encoding': 'gzip', 'Age': '11946', 'X-Cache': 'cp5008 miss, cp5011 hit/46', 'X-Cache-Status': 'hit-front', 'Server-Timing': 'cache;desc="hit-front"', 'Strict-Transport-Security': 'max-age=106384710; includeSubDomains; preload', 'Set-Cookie': 'WMF-Last-Access=29-May-2020;Path=/;HttpOnly;secure;Expires=Tue, 30 Jun 2020 00:00:00 GMT, WMF-Last-Access-Global=29-May-2020;Path=/;Domain=.wikipedia.org;HttpOnly;secure;Expires=Tue, 30 Jun 2020 00:00:00 GMT, GeoIP=IN:UP:Lucknow:26.84:80.92:v4; Path=/; secure; Domain=.wikipedia.org', 'X-Client-IP': '2409:4063:2103:cf7e:9c70:961b:6e8b:a779', 'Cache-Control': 'private, s-maxage=0, max-age=0, must-revalidate', 'Accept-Ranges': 'bytes', 'Content-Length': '12988', 'Connection': 'keep-alive'}

In [3]:
soup = BeautifulSoup(result.content, 'html.parser')
table = soup.find('table')
trs = table.find_all('tr')
rows = []
for tr in trs:
    i = tr.find_all('td')
    if i:
        rows.append(i)
        
lst = []
for row in rows:
    postalcode = row[0].text.rstrip()
    borough = row[1].text.rstrip()
    neighborhood = row[2].text.rstrip()
    if borough != 'Not assigned':
        if neighborhood == 'Not assigned':
            neighborhood = borough
        lst.append([postalcode, borough, neighborhood])

In [4]:
lst

[['M3A', 'North York', 'Parkwoods'],
 ['M4A', 'North York', 'Victoria Village'],
 ['M5A', 'Downtown Toronto', 'Regent Park, Harbourfront'],
 ['M6A', 'North York', 'Lawrence Manor, Lawrence Heights'],
 ['M7A', 'Downtown Toronto', "Queen's Park, Ontario Provincial Government"],
 ['M9A', 'Etobicoke', 'Islington Avenue, Humber Valley Village'],
 ['M1B', 'Scarborough', 'Malvern, Rouge'],
 ['M3B', 'North York', 'Don Mills'],
 ['M4B', 'East York', 'Parkview Hill, Woodbine Gardens'],
 ['M5B', 'Downtown Toronto', 'Garden District, Ryerson'],
 ['M6B', 'North York', 'Glencairn'],
 ['M9B',
  'Etobicoke',
  'West Deane Park, Princess Gardens, Martin Grove, Islington, Cloverdale'],
 ['M1C', 'Scarborough', 'Rouge Hill, Port Union, Highland Creek'],
 ['M3C', 'North York', 'Don Mills'],
 ['M4C', 'East York', 'Woodbine Heights'],
 ['M5C', 'Downtown Toronto', 'St. James Town'],
 ['M6C', 'York', 'Humewood-Cedarvale'],
 ['M9C',
  'Etobicoke',
  'Eringate, Bloordale Gardens, Old Burnhamthorpe, Markland Wood'],
 ['M1E', 'Scarborough', 'Guildwood, Morningside, West Hill'],
 ['M4E', 'East Toronto', 'The Beaches'],
 ['M5E', 'Downtown Toronto', 'Berczy Park'],
 ['M6E', 'York', 'Caledonia-Fairbanks'],
 ['M1G', 'Scarborough', 'Woburn'],
 ['M4G', 'East York', 'Leaside'],
 ['M5G', 'Downtown Toronto', 'Central Bay Street'],
 ['M6G', 'Downtown Toronto', 'Christie'],
 ['M1H', 'Scarborough', 'Cedarbrae'],
 ['M2H', 'North York', 'Hillcrest Village'],
 ['M3H', 'North York', 'Bathurst Manor, Wilson Heights, Downsview North'],
 ['M4H', 'East York', 'Thorncliffe Park'],
 ['M5H', 'Downtown Toronto', 'Richmond, Adelaide, King'],
 ['M6H', 'West Toronto', 'Dufferin, Dovercourt Village'],
 ['M1J', 'Scarborough', 'Scarborough Village'],
 ['M2J', 'North York', 'Fairview, Henry Farm, Oriole'],
 ['M3J', 'North York', 'Northwood Park, York University'],
 ['M4J', 'East York', 'East Toronto, Broadview North (Old East York)'],
 ['M5J',
  'Downtown Toronto',
  'Harbourfront East, Union Station, Toronto Islands'],
 ['M6J', 'West Toronto', 'Little Portugal, Trinity'],
 ['M1K', 'Scarborough', 'Kennedy Park, Ionview, East Birchmount Park'],
 ['M2K', 'North York', 'Bayview Village'],
 ['M3K', 'North York', 'Downsview'],
 ['M4K', 'East Toronto', 'The Danforth West, Riverdale'],
 ['M5K', 'Downtown Toronto', 'Toronto Dominion Centre, Design Exchange'],
 ['M6K', 'West Toronto', 'Brockton, Parkdale Village, Exhibition Place'],
 ['M1L', 'Scarborough', 'Golden Mile, Clairlea, Oakridge'],
 ['M2L', 'North York', 'York Mills, Silver Hills'],
 ['M3L', 'North York', 'Downsview'],
 ['M4L', 'East Toronto', 'India Bazaar, The Beaches West'],
 ['M5L', 'Downtown Toronto', 'Commerce Court, Victoria Hotel'],
 ['M6L', 'North York', 'North Park, Maple Leaf Park, Upwood Park'],
 ['M9L', 'North York', 'Humber Summit'],
 ['M1M', 'Scarborough', 'Cliffside, Cliffcrest, Scarborough Village West'],
 ['M2M', 'North York', 'Willowdale, Newtonbrook'],
 ['M3M', 'North York', 'Downsview'],
 ['M4M', 'East Toronto', 'Studio District'],
 ['M5M', 'North York', 'Bedford Park, Lawrence Manor East'],
 ['M6M', 'York', 'Del Ray, Mount Dennis, Keelsdale and Silverthorn'],
 ['M9M', 'North York', 'Humberlea, Emery'],
 ['M1N', 'Scarborough', 'Birch Cliff, Cliffside West'],
 ['M2N', 'North York', 'Willowdale, Willowdale East'],
 ['M3N', 'North York', 'Downsview'],
 ['M4N', 'Central Toronto', 'Lawrence Park'],
 ['M5N', 'Central Toronto', 'Roselawn'],
 ['M6N', 'York', 'Runnymede, The Junction North'],
 ['M9N', 'York', 'Weston'],
 ['M1P',
  'Scarborough',
  'Dorset Park, Wexford Heights, Scarborough Town Centre'],
 ['M2P', 'North York', 'York Mills West'],
 ['M4P', 'Central Toronto', 'Davisville North'],
 ['M5P', 'Central Toronto', 'Forest Hill North & West, Forest Hill Road Park'],
 ['M6P', 'West Toronto', 'High Park, The Junction South'],
 ['M9P', 'Etobicoke', 'Westmount'],
 ['M1R', 'Scarborough', 'Wexford, Maryvale'],
 ['M2R', 'North York', 'Willowdale, Willowdale West'],
 ['M4R', 'Central Toronto', 'North Toronto West,  Lawrence Park'],
 ['M5R', 'Central Toronto', 'The Annex, North Midtown, Yorkville'],
 ['M6R', 'West Toronto', 'Parkdale, Roncesvalles'],
 ['M7R', 'Mississauga', 'Canada Post Gateway Processing Centre'],
 ['M9R',
  'Etobicoke',
  'Kingsview Village, St. Phillips, Martin Grove Gardens, Richview Gardens'],
 ['M1S', 'Scarborough', 'Agincourt'],
 ['M4S', 'Central Toronto', 'Davisville'],
 ['M5S', 'Downtown Toronto', 'University of Toronto, Harbord'],
 ['M6S', 'West Toronto', 'Runnymede, Swansea'],
 ['M1T', 'Scarborough', "Clarks Corners, Tam O'Shanter, Sullivan"],
 ['M4T', 'Central Toronto', 'Moore Park, Summerhill East'],
 ['M5T', 'Downtown Toronto', 'Kensington Market, Chinatown, Grange Park'],
 ['M1V',
  'Scarborough',
  "Milliken, Agincourt North, Steeles East, L'Amoreaux East"],
 ['M4V',
  'Central Toronto',
  'Summerhill West, Rathnelly, South Hill, Forest Hill SE, Deer Park'],
 ['M5V',
  'Downtown Toronto',
  'CN Tower, King and Spadina, Railway Lands, Harbourfront West, Bathurst Quay, South Niagara, Island airport'],
 ['M8V', 'Etobicoke', 'New Toronto, Mimico South, Humber Bay Shores'],
 ['M9V',
  'Etobicoke',
  'South Steeles, Silverstone, Humbergate, Jamestown, Mount Olive, Beaumond Heights, Thistletown, Albion Gardens'],
 ['M1W', 'Scarborough', "Steeles West, L'Amoreaux West"],
 ['M4W', 'Downtown Toronto', 'Rosedale'],
 ['M5W', 'Downtown Toronto', 'Stn A PO Boxes'],
 ['M8W', 'Etobicoke', 'Alderwood, Long Branch'],
 ['M9W', 'Etobicoke', 'Northwest, West Humber - Clairville'],
 ['M1X', 'Scarborough', 'Upper Rouge'],
 ['M4X', 'Downtown Toronto', 'St. James Town, Cabbagetown'],
 ['M5X', 'Downtown Toronto', 'First Canadian Place, Underground city'],
 ['M8X', 'Etobicoke', 'The Kingsway, Montgomery Road, Old Mill North'],
 ['M4Y', 'Downtown Toronto', 'Church and Wellesley'],
 ['M7Y',
  'East Toronto',
  'Business reply mail Processing Centre, South Central Letter Processing Plant Toronto'],
 ['M8Y',
  'Etobicoke',
  "Old Mill South, King's Mill Park, Sunnylea, Humber Bay, Mimico NE, The Queensway East, Royal York South East, Kingsway Park South East"],
 ['M8Z',
  'Etobicoke',
  'Mimico NW, The Queensway West, South of Bloor, Kingsway Park South West, Royal York South West']]

In [5]:
cols = ['PostalCode', 'Borough', 'Neighborhood']
df = pd.DataFrame(lst, columns=cols)
print(df.shape)

(103, 3)

In [6]:
df[df.duplicated(['PostalCode'], keep=False)]

Empty DataFrame
Columns: [PostalCode, Borough, Neighborhood]
Index: []

In [7]:
df.shape

(103, 3)

In [8]:
df.head()

  PostalCode           Borough                                 Neighborhood
0        M3A        North York                                    Parkwoods
1        M4A        North York                             Victoria Village
2        M5A  Downtown Toronto                    Regent Park, Harbourfront
3        M6A        North York             Lawrence Manor, Lawrence Heights
4        M7A  Downtown Toronto  Queen's Park, Ontario Provincial Government

In [9]:
df = df.groupby('PostalCode').agg(
    {
        'Borough':'first', 
        'Neighborhood': ', '.join,}
    ).reset_index()

In [10]:
df.head()

  PostalCode      Borough                            Neighborhood
0        M1B  Scarborough                          Malvern, Rouge
1        M1C  Scarborough  Rouge Hill, Port Union, Highland Creek
2        M1E  Scarborough       Guildwood, Morningside, West Hill
3        M1G  Scarborough                                  Woburn
4        M1H  Scarborough                               Cedarbrae

In [11]:
df.loc[df['PostalCode'] == 'M5A']

   PostalCode           Borough               Neighborhood
53        M5A  Downtown Toronto  Regent Park, Harbourfront

In [13]:
dfgeo = pd.read_csv("Geospatial_Coordinates.csv")
dfgeo.rename(columns={'Postal Code': 'PostalCode'}, inplace=True)

In [14]:
df2 = pd.merge(df, dfgeo, on="PostalCode", how='left')

In [15]:
df2.loc[df2['PostalCode'] == 'M5G']

   PostalCode           Borough        Neighborhood   Latitude  Longitude
57        M5G  Downtown Toronto  Central Bay Street  43.657952 -79.387383

In [16]:
df2.loc[df2['PostalCode'] == 'M9V']

,PostalCode,Borough,Neighborhood,Latitude,Longitude
101,M9V,Etobicoke,"South Steeles, Silverstone, Humbergate, Jamest...",43.739416,-79.588437

In [18]:
CLIENT_ID = '4EXOHY0UN2FIDIKP252TJ5XDDJVJCJRHE20KBGD5OHEE330J'# Foursquare Id
CLIENT_SECRET = '5XBFB1YNTZPQ2JWZIU2BNTF3XCV3CW42T2E45CCKL55QF3N0' # Foursquare Secret
VERSION = '20180605' # API version

In [19]:
df2.set_index('PostalCode', inplace = True) 
neighborhood_latitude = df2.loc['M9V']['Latitude']
neighborhood_longitude = df2.loc['M9V']['Longitude']

In [20]:
LIMIT = 100 # limit of number of venues returned by Foursquare API
radius = 500 # define radius
# create URL
url = 'https://api.foursquare.com/v2/venues/explore?&client_id={}&client_secret={}&v={}&ll={},{}&radius={}&limit={}'.format(
    CLIENT_ID, 
    CLIENT_SECRET, 
    VERSION, 
    neighborhood_latitude, 
    neighborhood_longitude, 
    radius, 
    LIMIT)
url # display URL

'https://api.foursquare.com/v2/venues/explore?&client_id=4EXOHY0UN2FIDIKP252TJ5XDDJVJCJRHE20KBGD5OHEE330J&client_secret=5XBFB1YNTZPQ2JWZIU2BNTF3XCV3CW42T2E45CCKL55QF3N0&v=20180605&ll=43.739416399999996,-79.5884369&radius=500&limit=100'

In [21]:
results = requests.get(url).json()

In [22]:
# function that extracts the category of the venue
def get_category_type(row):
    try:
        categories_list = row['categories']
    except:
        categories_list = row['venue.categories']
        
    if len(categories_list) == 0:
        return None
    else:
        return categories_list[0]['name']

In [23]:
venues = results['response']['groups'][0]['items']

In [24]:
nearby_venues = json_normalize(venues) # flatten JSON
nearby_venues

E:\anaconda\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: pandas.io.json.json_normalize is deprecated, use pandas.json_normalize instead
  """Entry point for launching an IPython kernel.

,referralId,reasons.count,reasons.items,venue.id,venue.name,venue.location.address,venue.location.crossStreet,venue.location.lat,venue.location.lng,venue.location.labeledLatLngs,venue.location.distance,venue.location.postalCode,venue.location.cc,venue.location.city,venue.location.state,venue.location.country,venue.location.formattedAddress,venue.categories,venue.photos.count,venue.photos.groups
0,e-0-4c633939e1621b8d48842553-0,0,"[{'summary': 'This spot is popular', 'type': '...",4c633939e1621b8d48842553,Subway,"6210 Finch Ave West, Store 103",at Albion Rd.,43.742645,-79.589643,"[{'label': 'display', 'lat': 43.74264512142215...",372,M9V 0A1,CA,Toronto,ON,Canada,"[6210 Finch Ave West, Store 103 (at Albion Rd....","[{'id': '4bf58dd8d48988d1c5941735', 'name': 'S...",0,[]
1,e-0-4be58dc4cf200f479154133c-1,0,"[{'summary': 'This spot is popular', 'type': '...",4be58dc4cf200f479154133c,Shoppers Drug Mart,1530 Albion Rd,Albion Mall,43.741685,-79.584487,"[{'label': 'display', 'lat': 43.741685, 'lng':...",405,M9V 1B4,CA,Etobicoke,ON,Canada,"[1530 Albion Rd (Albion Mall), Etobicoke ON M9...","[{'id': '4bf58dd8d48988d10f951735', 'name': 'P...",0,[]
2,e-0-4be70e26cf200f47e334153c-2,0,"[{'summary': 'This spot is popular', 'type': '...",4be70e26cf200f47e334153c,Popeyes Louisiana Kitchen,1530 Albion Rd.,at Kipling Ave. (Albion Centre),43.741202,-79.584545,"[{'label': 'display', 'lat': 43.74120165509377...",370,M9V 1B4,CA,Etobicoke,ON,Canada,[1530 Albion Rd. (at Kipling Ave. (Albion Cent...,"[{'id': '4d4ae6fc7a7b7dea34424761', 'name': 'F...",0,[]
3,e-0-5112b872e4b0c0a78d7bcd27-3,0,"[{'summary': 'This spot is popular', 'type': '...",5112b872e4b0c0a78d7bcd27,Sunny Foodmart,1620 Albion road,Albion Road and Finch Ave,43.741840,-79.590561,"[{'label': 'display', 'lat': 43.74184023292111...",319,NaN,CA,Toronto,ON,Canada,"[1620 Albion road (Albion Road and Finch Ave),...","[{'id': '4bf58dd8d48988d118951735', 'name': 'G...",0,[]
4,e-0-4cd4738cdfb4a1cd4337535c-4,0,"[{'summary': 'This spot is popular', 'type': '...",4cd4738cdfb4a1cd4337535c,The Beer Store,1530 Albion Rd,Near Finch Ave. W.,43.741694,-79.584373,"[{'label': 'display', 'lat': 43.7416936, 'lng'...",413,M9V 1B4,CA,Etobicoke,ON,Canada,"[1530 Albion Rd (Near Finch Ave. W.), Etobicok...","[{'id': '5370f356bcbc57f1066c94c2', 'name': 'B...",0,[]
5,e-0-4b04a05bf964a520c45522e3-5,0,"[{'summary': 'This spot is popular', 'type': '...",4b04a05bf964a520c45522e3,Sheriff's No Frills,1530 Albion Rd,at Finch Ave. W.,43.741696,-79.584379,"[{'label': 'display', 'lat': 43.741696, 'lng':...",413,M9V 1B4,CA,Etobicoke,ON,Canada,"[1530 Albion Rd (at Finch Ave. W.), Etobicoke ...","[{'id': '4bf58dd8d48988d118951735', 'name': 'G...",0,[]
6,e-0-4d8ba6910c4e41bdaaf7667f-6,0,"[{'summary': 'This spot is popular', 'type': '...",4d8ba6910c4e41bdaaf7667f,Pizza Pizza,"1530 Albion Road, Unit T25",NaN,43.741569,-79.584489,"[{'label': 'display', 'lat': 43.74156896801906...",397,M9V 1B4,CA,Etobicoke,ON,Canada,"[1530 Albion Road, Unit T25, Etobicoke ON M9V ...","[{'id': '4bf58dd8d48988d1ca941735', 'name': 'P...",0,[]
7,e-0-4c1951d6834e2d7f2d3a2a80-7,0,"[{'summary': 'This spot is popular', 'type': '...",4c1951d6834e2d7f2d3a2a80,McDonald's,"1530 Albion Road, Unit F-1",NaN,43.741757,-79.584230,"[{'label': 'display', 'lat': 43.7417571, 'lng'...",427,M9V 1B4,CA,Toronto,ON,Canada,"[1530 Albion Road, Unit F-1, Toronto ON M9V 1B...","[{'id': '4bf58dd8d48988d16e941735', 'name': 'F...",0,[]
8,e-0-4f035c5c5c5c51dd31b52e55-8,0,"[{'summary': 'This spot is popular', 'type': '...",4f035c5c5c5c51dd31b52e55,Dollarama,"1620 Albion Rd, Finch Albion Centre",NaN,43.742018,-79.591076,"[{'label': 'display', 'lat': 43.742018, 'lng':...",359,M9V 4B4,CA,Etobicoke,ON,Canada,"[1620 Albion Rd, Finch Albion Centre, Etobicok...","[{'id': '52dea92d3cf9994f4e043dbb', 'name': 'D...",0,[]
9,e-0-54e521a9498e559c968e8083-9,0,"[{'summary': 'This spot is popular', 'type': '...",54e521a9498e559c968e8083,NORI SUSHI,NaN,NaN,43.742775,-79.586985,"[{'label': 'display', 'lat': 43.742775, 'lng':...",391,NaN,CA,NaN,NaN,Canada,[Canada],"[{'id': '4bf58dd8d48988d111941735', 'name': 'J...",0,[]
10,e-0-4ce971bff8653704e40db7c4-10,0,"[{'summary': 'This spot is popular', 'type': '...",4ce971bff8653704e40db7c4,LCBO,Albion Mall,1530 Albion Rd,43.741508,-79.584501,"[{'label': 'display', 'lat': 43.74150752194671...",392,M9V 1B4,CA,Toronto,ON,Canada,"[Albion Mall (1530 Albion Rd), Toronto ON M9V ...","[{'id': '4bf58dd8d48988d186941735', 'name': 'L...",0,[]

In [25]:
filtered_columns = ['venue.name', 'venue.categories', 'venue.location.lat', 'venue.location.lng']
nearby_venues = nearby_venues.loc[:, filtered_columns]

# filter the category for each row
nearby_venues['venue.categories'] = nearby_venues.apply(get_category_type, axis=1)

# clean columns
nearby_venues.columns = [col.split(".")[-1] for col in nearby_venues.columns]

nearby_venues.head()

                        name           categories        lat        lng
0                     Subway       Sandwich Place  43.742645 -79.589643
1         Shoppers Drug Mart             Pharmacy  43.741685 -79.584487
2  Popeyes Louisiana Kitchen  Fried Chicken Joint  43.741202 -79.584545
3             Sunny Foodmart        Grocery Store  43.741840 -79.590561
4             The Beer Store           Beer Store  43.741694 -79.584373

In [26]:
print('{} venues were returned by Foursquare.'.format(nearby_venues.shape[0]))

11 venues were returned by Foursquare.

In [27]:
def getNearbyVenues(names, latitudes, longitudes, radius=500):
    
    venues_list=[]
    for name, lat, lng in zip(names, latitudes, longitudes):
        print(name)
            
        # create the API request URL
        url = 'https://api.foursquare.com/v2/venues/explore?&client_id={}&client_secret={}&v={}&ll={},{}&radius={}&limit={}'.format(
            CLIENT_ID, 
            CLIENT_SECRET, 
            VERSION, 
            lat, 
            lng, 
            radius, 
            LIMIT)
            
        # make the GET request
        results = requests.get(url).json()["response"]['groups'][0]['items']
        
        # return only relevant information for each nearby venue
        venues_list.append([(
            name, 
            lat, 
            lng, 
            v['venue']['name'], 
            v['venue']['location']['lat'], 
            v['venue']['location']['lng'],  
            v['venue']['categories'][0]['name']) for v in results])

    nearby_venues = pd.DataFrame([item for venue_list in venues_list for item in venue_list])
    nearby_venues.columns = ['Neighborhood', 
                  'Neighborhood Latitude', 
                  'Neighborhood Longitude', 
                  'Venue', 
                  'Venue Latitude', 
                  'Venue Longitude', 
                  'Venue Category']
    
    return(nearby_venues)

In [28]:
df2

,Borough,Neighborhood,Latitude,Longitude
PostalCode,,,,
M1B,Scarborough,"Malvern, Rouge",43.806686,-79.194353
M1C,Scarborough,"Rouge Hill, Port Union, Highland Creek",43.784535,-79.160497
M1E,Scarborough,"Guildwood, Morningside, West Hill",43.763573,-79.188711
M1G,Scarborough,Woburn,43.770992,-79.216917
M1H,Scarborough,Cedarbrae,43.773136,-79.239476
...,...,...,...,...
M9N,York,Weston,43.706876,-79.518188
M9P,Etobicoke,Westmount,43.696319,-79.532242
M9R,Etobicoke,"Kingsview Village, St. Phillips, Martin Grove ...",43.688905,-79.554724
M9V,Etobicoke,"South Steeles, Silverstone, Humbergate, Jamest...",43.739416,-79.588437
M9W,Etobicoke,"Northwest, West Humber - Clairville",43.706748,-79.594054